<Project>
  <PropertyGroup>
    <!-- Common build settings -->
    <LangVersion>latest</LangVersion>
    <!-- TargetFramework(s) set in subdirectory Directory.Build.props files -->
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <DebugType>embedded</DebugType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>

    <!-- Common assembly information -->
    <Company>Universities of Dundee and Edinburgh</Company>
    <Product>DicomTypeTranslation</Product>
    <Copyright>Copyright © 2020-2025</Copyright>
    <Version>5.0.1</Version>
    <AssemblyVersion>5.0.1</AssemblyVersion>
    <FileVersion>5.0.1</FileVersion>
    <InformationalVersion>5.0.1</InformationalVersion>

    <!-- Enable Central Package Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Release configuration settings -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>embedded</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>
</Project>
