name: .NET Core

on:
  push:
  schedule:
    - cron: "59 14 * * 2"

env:
  MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
  ACCEPT_EULA: "Y"
  MSSQL_PID: "developer"

jobs:
  build:

    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: write
      security-events: write

    steps:
    - name: Disable disk flush for CI
      run: sudo apt-get install -y libeatmydata1
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
    - name: Update Directory.Build.props for SDK version
      run: ./scripts/generate-build-props.sh
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: csharp
        queries: +security-and-quality
    - name: Install MS SQL Server and Postgresql, start existing MySQL
      run: |
        curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --yes --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
        curl -fsSL https://packages.microsoft.com/config/ubuntu/24.04/mssql-server-preview.list | sudo tee /etc/apt/sources.list.d/mssql-server-preview.list
        sudo apt-get update
        ACCEPT_EULA=y sudo apt-get install -qqy mssql-tools18 unixodbc-dev mssql-server --no-install-recommends
        sed -i -e 's/Pwd=;/Pwd=root;AllowPublicKeyRetrieval=True;/' DicomTypeTranslation.Tests/TestDatabases.xml
        sudo apt-get install -y --no-install-recommends postgresql mssql-server
        sudo -E /opt/mssql/bin/mssql-conf -n setup accept-eula
        sudo service mysql start
    - name: Build
      run: dotnet build --configuration Release --nologo
    - name: Test
      run: dotnet test --configuration Release --verbosity normal --nologo --collect:"XPlat Code Coverage" --results-directory ./coverage
    - name: Codecov
      uses: codecov/codecov-action@v7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        category: "/language:csharp"
    - name: Pack and push
      if: contains(github.ref,'refs/tags/')
      run: |
        dotnet pack DicomTypeTranslation/DicomTypeTranslation.csproj -c Release -p:DebugType=full -p:SymbolPackageFormat=snupkg --include-source --include-symbols -o dist
        dotnet nuget push dist/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
